In [1]:
# import libraries
import pandas as pd
import numpy as np

In [3]:
import os

os.listdir("../data/raw")

['Airline Delay Cause',
 'Customer Support on Twitter',
 'Twitter US Airline Sentiment']

In [4]:
os.listdir("../data/raw/Twitter US Airline Sentiment")

['database.sqlite', 'Tweets.csv']

In [5]:
airline_df = pd.read_csv(
    "../data/raw/Twitter US Airline Sentiment/Tweets.csv"
)

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [6]:
airline_df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [ ]:
# Dataset Shape(rows, columns)
airline_df.shape

(14640, 15)

In [9]:
# View Column Names
airline_df.columns

Index(['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence',
       'negativereason', 'negativereason_confidence', 'airline',
       'airline_sentiment_gold', 'name', 'negativereason_gold',
       'retweet_count', 'text', 'tweet_coord', 'tweet_created',
       'tweet_location', 'user_timezone'],
      dtype='str')

In [10]:
# Keep Important Columns Only
airline_df = airline_df[
    [
        "airline",
        "text",
        "airline_sentiment",
        "negativereason"
    ]
]

airline_df.head()

,airline,text,airline_sentiment,negativereason
0,Virgin America,@VirginAmerica What @dhepburn said.,neutral,NaN
1,Virgin America,@VirginAmerica plus you've added commercials t...,positive,NaN
2,Virgin America,@VirginAmerica I didn't today... Must mean I n...,neutral,NaN
3,Virgin America,@VirginAmerica it's really aggressive to blast...,negative,Bad Flight
4,Virgin America,@VirginAmerica and it's a really big bad thing...,negative,Can't Tell

In [11]:
# Check Missing Values
airline_df.isnull().sum()

airline                 0
text                    0
airline_sentiment       0
negativereason       5462
dtype: int64

In [12]:
# Remove Missing Text
airline_df = airline_df.dropna(subset=["text"])

print("Missing text rows removed!")

Missing text rows removed!

In [13]:
# Explore Sentiment Distribution
airline_df["airline_sentiment"].value_counts()

airline_sentiment
negative    9178
neutral     3099
positive    2363
Name: count, dtype: int64

In [14]:
# Explore Complaint Categories
airline_df["negativereason"].value_counts()

negativereason
Customer Service Issue         2910
Late Flight                    1665
Can't Tell                     1190
Cancelled Flight                847
Lost Luggage                    724
Bad Flight                      580
Flight Booking Problems         529
Flight Attendant Complaints     481
longlines                       178
Damaged Luggage                  74
Name: count, dtype: int64